### ISSUE TITLE
Learn how to fetch files from repo

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/kira#24]
## What needs to be done?

We store `.kira.yml` configuration file inside each repo.
It contains:
- rates
- roles
- several assignment rules, etc

For now we need to implement API call to fetch this file from Gitlab.
We should only care for `master` branch.

**Comment by YarNayar** [comment]
I will do it this week

**Comment by YarNayar** [comment]
To fetch given file content we need to `GET /projects/:project_id/repository/files/:file_path/raw?ref=master` to `https://#{gitlab_host}/#{api_endpoint}`

where:
- `project_id` - either integer project id or URL-encoded pair of :namespace/:project_name
- `filepath` - URL-encoded path to file

Source: 
https://docs.gitlab.com/ce/api/repository_files.html#get-raw-file-from-repository

Here is a quick demo which is working on the current version on GitLab:

```
defmodule FetchGitlabFile do
  @gitlab_host "https://gitlab.com"
  @api_endpoint "api/v4"
  @access_token "<ACCESS_TOKEN>"
  # @project_id "12644038"
  @project_id "YarTestBot/test-private-project"  # accepts two form: integer ID and URL-encoded :namespace/:project_name
  @filepath "kira.yaml" # must be encoded if

  def encode(param) do
    param
    |> URI.encode_www_form()
  end

  def client do
    middleware = [
      {Tesla.Middleware.BaseUrl, @gitlab_host},
      {Tesla.Middleware.Headers, [{"PRIVATE-TOKEN", @access_token }]}
    ]

    Tesla.client(middleware)
  end

  def api_path do
    "/#{@api_endpoint}/projects/#{encode(@project_id)}/repository/files/#{encode(@filepath)}/raw?ref=master"
  end


  def fetch_file do
    client
    |> Tesla.get(api_path())
    |> IO.inspect()
  end
end
```
```
defmodule FetchGitlabFileTest do
  use ExUnit.Case

  test "fetches file" do
    {:ok, %{body: body}} = FetchGitlabFile.fetch_file()
    expected_content = "# My config is here\n"
    assert body == expected_content
  end
end
```

**Comment by YarNayar** [comment]
Hey, @sobolevn how do we resolve this issue? The title says "Learn how...", so is it sufficient to close it or should I implement the described feature?

**Comment by sobolevn** [comment]
Yes, let's implement it. Thanks for making a research!

**Comment by YarNayar** [comment]
@sobolevn Hey, I kinda stuck with an otherwise trivial issue and wondering maybe you could drop a couple of hints. I don't quite get how I suppose to use HTTP/Gitlab mocks in the tests. I'm familiar with  [2015 Jose's blog post](http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/) on which Mox is based and would expect to have something like 'config :whatever, Client' and `config :whatever, MockClient` for different environments for either HTTP or GITLAB client, but since I'm quite new to Elixir world, whole `defmacro mock(module)` in `TeslaMock` confises me, I'm not sure how I suppose to use it. I guess I'll figure it out over time, but it would be cool if you gave some examples on how to use it or any other helpful material on that matter. Thanks.

**Comment by sobolevn** [comment]
Maybe source code can help you?
1. https://github.com/wemake-services/kira/blob/master/test/test_helper.exs#L18-L21
2. https://github.com/wemake-services/kira/blob/101be5f619f467d75437a506dd7e5e6cf6661e2a/test/kira/usecases/renew_project_users_test.exs#L27-L31

That's all you need to do.
